/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedHospitalsRouteImport } from './routes/_authenticated/hospitals'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedSalesRepsIndexRouteImport } from './routes/_authenticated/sales-reps.index'
import { Route as AuthenticatedPoliciesIndexRouteImport } from './routes/_authenticated/policies.index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments.index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents.index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiPublicPdfSmokeRouteImport } from './routes/api/public/pdf-smoke'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as AuthenticatedSalesRepsRepIdRouteImport } from './routes/_authenticated/sales-reps.$repId'
import { Route as AuthenticatedPoliciesNewRouteImport } from './routes/_authenticated/policies.new'
import { Route as AuthenticatedPoliciesPolicyIdRouteImport } from './routes/_authenticated/policies.$policyId'
import { Route as AuthenticatedPaymentsPaymentIdRouteImport } from './routes/_authenticated/payments.$paymentId'
import { Route as AuthenticatedIncidentsNewRouteImport } from './routes/_authenticated/incidents.new'
import { Route as AuthenticatedIncidentsDashboardRouteImport } from './routes/_authenticated/incidents.dashboard'
import { Route as AuthenticatedIncidentsIncidentIdRouteImport } from './routes/_authenticated/incidents.$incidentId'
import { Route as AuthenticatedCompaniesCompanyIdRouteImport } from './routes/_authenticated/companies.$companyId'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as ApiPublicHooksSheetsSyncRouteImport } from './routes/api/public/hooks/sheets-sync'
import { Route as ApiPublicHooksPaymentHousekeepingRouteImport } from './routes/api/public/hooks/payment-housekeeping'
import { Route as ApiPublicHooksPassExpirationRouteImport } from './routes/api/public/hooks/pass-expiration'
import { Route as ApiPublicHooksBankReconciliationRouteImport } from './routes/api/public/hooks/bank-reconciliation'
import { Route as AuthenticatedAdminIntegrationsGoogleSheetsRouteImport } from './routes/_authenticated/admin.integrations.google-sheets'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHospitalsRoute = AuthenticatedHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRepsIndexRoute =
  AuthenticatedSalesRepsIndexRouteImport.update({
    id: '/sales-reps/',
    path: '/sales-reps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliciesIndexRoute =
  AuthenticatedPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiPublicPdfSmokeRoute = ApiPublicPdfSmokeRouteImport.update({
  id: '/api/public/pdf-smoke',
  path: '/api/public/pdf-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesRepsRepIdRoute =
  AuthenticatedSalesRepsRepIdRouteImport.update({
    id: '/sales-reps/$repId',
    path: '/sales-reps/$repId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPoliciesNewRoute =
  AuthenticatedPoliciesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesPolicyIdRoute =
  AuthenticatedPoliciesPolicyIdRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPaymentsPaymentIdRoute =
  AuthenticatedPaymentsPaymentIdRouteImport.update({
    id: '/$paymentId',
    path: '/$paymentId',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedIncidentsNewRoute =
  AuthenticatedIncidentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedIncidentsDashboardRoute =
  AuthenticatedIncidentsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedIncidentsIncidentIdRoute =
  AuthenticatedIncidentsIncidentIdRouteImport.update({
    id: '/$incidentId',
    path: '/$incidentId',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdRoute =
  AuthenticatedCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiPublicHooksSheetsSyncRoute =
  ApiPublicHooksSheetsSyncRouteImport.update({
    id: '/api/public/hooks/sheets-sync',
    path: '/api/public/hooks/sheets-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaymentHousekeepingRoute =
  ApiPublicHooksPaymentHousekeepingRouteImport.update({
    id: '/api/public/hooks/payment-housekeeping',
    path: '/api/public/hooks/payment-housekeeping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPassExpirationRoute =
  ApiPublicHooksPassExpirationRouteImport.update({
    id: '/api/public/hooks/pass-expiration',
    path: '/api/public/hooks/pass-expiration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBankReconciliationRoute =
  ApiPublicHooksBankReconciliationRouteImport.update({
    id: '/api/public/hooks/bank-reconciliation',
    path: '/api/public/hooks/bank-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIntegrationsGoogleSheetsRoute =
  AuthenticatedAdminIntegrationsGoogleSheetsRouteImport.update({
    id: '/admin/integrations/google-sheets',
    path: '/admin/integrations/google-sheets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hospitals': typeof AuthenticatedHospitalsRoute
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/dashboard': typeof AuthenticatedIncidentsDashboardRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/policies/$policyId': typeof AuthenticatedPoliciesPolicyIdRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/sales-reps/$repId': typeof AuthenticatedSalesRepsRepIdRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/pdf-smoke': typeof ApiPublicPdfSmokeRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/sales-reps/': typeof AuthenticatedSalesRepsIndexRoute
  '/admin/integrations/google-sheets': typeof AuthenticatedAdminIntegrationsGoogleSheetsRoute
  '/api/public/hooks/bank-reconciliation': typeof ApiPublicHooksBankReconciliationRoute
  '/api/public/hooks/pass-expiration': typeof ApiPublicHooksPassExpirationRoute
  '/api/public/hooks/payment-housekeeping': typeof ApiPublicHooksPaymentHousekeepingRoute
  '/api/public/hooks/sheets-sync': typeof ApiPublicHooksSheetsSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hospitals': typeof AuthenticatedHospitalsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/dashboard': typeof AuthenticatedIncidentsDashboardRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/policies/$policyId': typeof AuthenticatedPoliciesPolicyIdRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/sales-reps/$repId': typeof AuthenticatedSalesRepsRepIdRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/pdf-smoke': typeof ApiPublicPdfSmokeRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
  '/sales-reps': typeof AuthenticatedSalesRepsIndexRoute
  '/admin/integrations/google-sheets': typeof AuthenticatedAdminIntegrationsGoogleSheetsRoute
  '/api/public/hooks/bank-reconciliation': typeof ApiPublicHooksBankReconciliationRoute
  '/api/public/hooks/pass-expiration': typeof ApiPublicHooksPassExpirationRoute
  '/api/public/hooks/payment-housekeeping': typeof ApiPublicHooksPaymentHousekeepingRoute
  '/api/public/hooks/sheets-sync': typeof ApiPublicHooksSheetsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/hospitals': typeof AuthenticatedHospitalsRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/_authenticated/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/_authenticated/incidents/dashboard': typeof AuthenticatedIncidentsDashboardRoute
  '/_authenticated/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/_authenticated/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/_authenticated/policies/$policyId': typeof AuthenticatedPoliciesPolicyIdRoute
  '/_authenticated/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/_authenticated/sales-reps/$repId': typeof AuthenticatedSalesRepsRepIdRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/api/public/pdf-smoke': typeof ApiPublicPdfSmokeRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/_authenticated/sales-reps/': typeof AuthenticatedSalesRepsIndexRoute
  '/_authenticated/admin/integrations/google-sheets': typeof AuthenticatedAdminIntegrationsGoogleSheetsRoute
  '/api/public/hooks/bank-reconciliation': typeof ApiPublicHooksBankReconciliationRoute
  '/api/public/hooks/pass-expiration': typeof ApiPublicHooksPassExpirationRoute
  '/api/public/hooks/payment-housekeeping': typeof ApiPublicHooksPaymentHousekeepingRoute
  '/api/public/hooks/sheets-sync': typeof ApiPublicHooksSheetsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/clients'
    | '/dashboard'
    | '/finance'
    | '/hospitals'
    | '/incidents'
    | '/messages'
    | '/payments'
    | '/policies'
    | '/reports'
    | '/settings'
    | '/clients/$clientId'
    | '/clients/new'
    | '/companies/$companyId'
    | '/incidents/$incidentId'
    | '/incidents/dashboard'
    | '/incidents/new'
    | '/payments/$paymentId'
    | '/policies/$policyId'
    | '/policies/new'
    | '/sales-reps/$repId'
    | '/api/public/bootstrap'
    | '/api/public/pdf-smoke'
    | '/clients/'
    | '/companies/'
    | '/incidents/'
    | '/payments/'
    | '/policies/'
    | '/sales-reps/'
    | '/admin/integrations/google-sheets'
    | '/api/public/hooks/bank-reconciliation'
    | '/api/public/hooks/pass-expiration'
    | '/api/public/hooks/payment-housekeeping'
    | '/api/public/hooks/sheets-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alerts'
    | '/dashboard'
    | '/finance'
    | '/hospitals'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/clients/$clientId'
    | '/clients/new'
    | '/companies/$companyId'
    | '/incidents/$incidentId'
    | '/incidents/dashboard'
    | '/incidents/new'
    | '/payments/$paymentId'
    | '/policies/$policyId'
    | '/policies/new'
    | '/sales-reps/$repId'
    | '/api/public/bootstrap'
    | '/api/public/pdf-smoke'
    | '/clients'
    | '/companies'
    | '/incidents'
    | '/payments'
    | '/policies'
    | '/sales-reps'
    | '/admin/integrations/google-sheets'
    | '/api/public/hooks/bank-reconciliation'
    | '/api/public/hooks/pass-expiration'
    | '/api/public/hooks/payment-housekeeping'
    | '/api/public/hooks/sheets-sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/hospitals'
    | '/_authenticated/incidents'
    | '/_authenticated/messages'
    | '/_authenticated/payments'
    | '/_authenticated/policies'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/companies/$companyId'
    | '/_authenticated/incidents/$incidentId'
    | '/_authenticated/incidents/dashboard'
    | '/_authenticated/incidents/new'
    | '/_authenticated/payments/$paymentId'
    | '/_authenticated/policies/$policyId'
    | '/_authenticated/policies/new'
    | '/_authenticated/sales-reps/$repId'
    | '/api/public/bootstrap'
    | '/api/public/pdf-smoke'
    | '/_authenticated/clients/'
    | '/_authenticated/companies/'
    | '/_authenticated/incidents/'
    | '/_authenticated/payments/'
    | '/_authenticated/policies/'
    | '/_authenticated/sales-reps/'
    | '/_authenticated/admin/integrations/google-sheets'
    | '/api/public/hooks/bank-reconciliation'
    | '/api/public/hooks/pass-expiration'
    | '/api/public/hooks/payment-housekeeping'
    | '/api/public/hooks/sheets-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
  ApiPublicPdfSmokeRoute: typeof ApiPublicPdfSmokeRoute
  ApiPublicHooksBankReconciliationRoute: typeof ApiPublicHooksBankReconciliationRoute
  ApiPublicHooksPassExpirationRoute: typeof ApiPublicHooksPassExpirationRoute
  ApiPublicHooksPaymentHousekeepingRoute: typeof ApiPublicHooksPaymentHousekeepingRoute
  ApiPublicHooksSheetsSyncRoute: typeof ApiPublicHooksSheetsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hospitals': {
      id: '/_authenticated/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof AuthenticatedHospitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-reps/': {
      id: '/_authenticated/sales-reps/'
      path: '/sales-reps'
      fullPath: '/sales-reps/'
      preLoaderRoute: typeof AuthenticatedSalesRepsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies/': {
      id: '/_authenticated/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof AuthenticatedPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/pdf-smoke': {
      id: '/api/public/pdf-smoke'
      path: '/api/public/pdf-smoke'
      fullPath: '/api/public/pdf-smoke'
      preLoaderRoute: typeof ApiPublicPdfSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales-reps/$repId': {
      id: '/_authenticated/sales-reps/$repId'
      path: '/sales-reps/$repId'
      fullPath: '/sales-reps/$repId'
      preLoaderRoute: typeof AuthenticatedSalesRepsRepIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies/new': {
      id: '/_authenticated/policies/new'
      path: '/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof AuthenticatedPoliciesNewRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/$policyId': {
      id: '/_authenticated/policies/$policyId'
      path: '/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof AuthenticatedPoliciesPolicyIdRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/payments/$paymentId': {
      id: '/_authenticated/payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/incidents/new': {
      id: '/_authenticated/incidents/new'
      path: '/new'
      fullPath: '/incidents/new'
      preLoaderRoute: typeof AuthenticatedIncidentsNewRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/incidents/dashboard': {
      id: '/_authenticated/incidents/dashboard'
      path: '/dashboard'
      fullPath: '/incidents/dashboard'
      preLoaderRoute: typeof AuthenticatedIncidentsDashboardRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/incidents/$incidentId': {
      id: '/_authenticated/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/companies/$companyId': {
      id: '/_authenticated/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/hooks/sheets-sync': {
      id: '/api/public/hooks/sheets-sync'
      path: '/api/public/hooks/sheets-sync'
      fullPath: '/api/public/hooks/sheets-sync'
      preLoaderRoute: typeof ApiPublicHooksSheetsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/payment-housekeeping': {
      id: '/api/public/hooks/payment-housekeeping'
      path: '/api/public/hooks/payment-housekeeping'
      fullPath: '/api/public/hooks/payment-housekeeping'
      preLoaderRoute: typeof ApiPublicHooksPaymentHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pass-expiration': {
      id: '/api/public/hooks/pass-expiration'
      path: '/api/public/hooks/pass-expiration'
      fullPath: '/api/public/hooks/pass-expiration'
      preLoaderRoute: typeof ApiPublicHooksPassExpirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bank-reconciliation': {
      id: '/api/public/hooks/bank-reconciliation'
      path: '/api/public/hooks/bank-reconciliation'
      fullPath: '/api/public/hooks/bank-reconciliation'
      preLoaderRoute: typeof ApiPublicHooksBankReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/integrations/google-sheets': {
      id: '/_authenticated/admin/integrations/google-sheets'
      path: '/admin/integrations/google-sheets'
      fullPath: '/admin/integrations/google-sheets'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsGoogleSheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedIncidentsRouteChildren {
  AuthenticatedIncidentsIncidentIdRoute: typeof AuthenticatedIncidentsIncidentIdRoute
  AuthenticatedIncidentsDashboardRoute: typeof AuthenticatedIncidentsDashboardRoute
  AuthenticatedIncidentsNewRoute: typeof AuthenticatedIncidentsNewRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
}

const AuthenticatedIncidentsRouteChildren: AuthenticatedIncidentsRouteChildren =
  {
    AuthenticatedIncidentsIncidentIdRoute:
      AuthenticatedIncidentsIncidentIdRoute,
    AuthenticatedIncidentsDashboardRoute: AuthenticatedIncidentsDashboardRoute,
    AuthenticatedIncidentsNewRoute: AuthenticatedIncidentsNewRoute,
    AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  }

const AuthenticatedIncidentsRouteWithChildren =
  AuthenticatedIncidentsRoute._addFileChildren(
    AuthenticatedIncidentsRouteChildren,
  )

interface AuthenticatedPaymentsRouteChildren {
  AuthenticatedPaymentsPaymentIdRoute: typeof AuthenticatedPaymentsPaymentIdRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
}

const AuthenticatedPaymentsRouteChildren: AuthenticatedPaymentsRouteChildren = {
  AuthenticatedPaymentsPaymentIdRoute: AuthenticatedPaymentsPaymentIdRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
}

const AuthenticatedPaymentsRouteWithChildren =
  AuthenticatedPaymentsRoute._addFileChildren(
    AuthenticatedPaymentsRouteChildren,
  )

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesPolicyIdRoute: typeof AuthenticatedPoliciesPolicyIdRoute
  AuthenticatedPoliciesNewRoute: typeof AuthenticatedPoliciesNewRoute
  AuthenticatedPoliciesIndexRoute: typeof AuthenticatedPoliciesIndexRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesPolicyIdRoute: AuthenticatedPoliciesPolicyIdRoute,
  AuthenticatedPoliciesNewRoute: AuthenticatedPoliciesNewRoute,
  AuthenticatedPoliciesIndexRoute: AuthenticatedPoliciesIndexRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHospitalsRoute: typeof AuthenticatedHospitalsRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRouteWithChildren
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCompaniesCompanyIdRoute: typeof AuthenticatedCompaniesCompanyIdRoute
  AuthenticatedSalesRepsRepIdRoute: typeof AuthenticatedSalesRepsRepIdRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedSalesRepsIndexRoute: typeof AuthenticatedSalesRepsIndexRoute
  AuthenticatedAdminIntegrationsGoogleSheetsRoute: typeof AuthenticatedAdminIntegrationsGoogleSheetsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHospitalsRoute: AuthenticatedHospitalsRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRouteWithChildren,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCompaniesCompanyIdRoute: AuthenticatedCompaniesCompanyIdRoute,
  AuthenticatedSalesRepsRepIdRoute: AuthenticatedSalesRepsRepIdRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedSalesRepsIndexRoute: AuthenticatedSalesRepsIndexRoute,
  AuthenticatedAdminIntegrationsGoogleSheetsRoute:
    AuthenticatedAdminIntegrationsGoogleSheetsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
  ApiPublicPdfSmokeRoute: ApiPublicPdfSmokeRoute,
  ApiPublicHooksBankReconciliationRoute: ApiPublicHooksBankReconciliationRoute,
  ApiPublicHooksPassExpirationRoute: ApiPublicHooksPassExpirationRoute,
  ApiPublicHooksPaymentHousekeepingRoute:
    ApiPublicHooksPaymentHousekeepingRoute,
  ApiPublicHooksSheetsSyncRoute: ApiPublicHooksSheetsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
