/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPoliciesRouteImport } from './routes/_authenticated/policies'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedPoliciesIndexRouteImport } from './routes/_authenticated/policies.index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments.index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiPublicPdfSmokeRouteImport } from './routes/api/public/pdf-smoke'
import { Route as AuthenticatedPoliciesNewRouteImport } from './routes/_authenticated/policies.new'
import { Route as AuthenticatedPoliciesPolicyIdRouteImport } from './routes/_authenticated/policies.$policyId'
import { Route as AuthenticatedPaymentsDashboardRouteImport } from './routes/_authenticated/payments.dashboard'
import { Route as AuthenticatedPaymentsPaymentIdRouteImport } from './routes/_authenticated/payments.$paymentId'
import { Route as AuthenticatedIncidentsNewRouteImport } from './routes/_authenticated/incidents.new'
import { Route as AuthenticatedIncidentsDashboardRouteImport } from './routes/_authenticated/incidents.dashboard'
import { Route as AuthenticatedIncidentsIncidentIdRouteImport } from './routes/_authenticated/incidents.$incidentId'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSeedDemoRouteImport } from './routes/_authenticated/admin.seed-demo'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as ApiPublicHooksPaymentHousekeepingRouteImport } from './routes/api/public/hooks/payment-housekeeping'
import { Route as ApiPublicHooksPassExpirationRouteImport } from './routes/api/public/hooks/pass-expiration'
import { Route as ApiPublicHooksBankReconciliationRouteImport } from './routes/api/public/hooks/bank-reconciliation'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesRoute = AuthenticatedPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoliciesIndexRoute =
  AuthenticatedPoliciesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiPublicPdfSmokeRoute = ApiPublicPdfSmokeRouteImport.update({
  id: '/api/public/pdf-smoke',
  path: '/api/public/pdf-smoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPoliciesNewRoute =
  AuthenticatedPoliciesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPoliciesPolicyIdRoute =
  AuthenticatedPoliciesPolicyIdRouteImport.update({
    id: '/$policyId',
    path: '/$policyId',
    getParentRoute: () => AuthenticatedPoliciesRoute,
  } as any)
const AuthenticatedPaymentsDashboardRoute =
  AuthenticatedPaymentsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedPaymentsPaymentIdRoute =
  AuthenticatedPaymentsPaymentIdRouteImport.update({
    id: '/$paymentId',
    path: '/$paymentId',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedIncidentsNewRoute =
  AuthenticatedIncidentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedIncidentsDashboardRoute =
  AuthenticatedIncidentsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedIncidentsIncidentIdRoute =
  AuthenticatedIncidentsIncidentIdRouteImport.update({
    id: '/$incidentId',
    path: '/$incidentId',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSeedDemoRoute =
  AuthenticatedAdminSeedDemoRouteImport.update({
    id: '/admin/seed-demo',
    path: '/admin/seed-demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const ApiPublicHooksPaymentHousekeepingRoute =
  ApiPublicHooksPaymentHousekeepingRouteImport.update({
    id: '/api/public/hooks/payment-housekeeping',
    path: '/api/public/hooks/payment-housekeeping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPassExpirationRoute =
  ApiPublicHooksPassExpirationRouteImport.update({
    id: '/api/public/hooks/pass-expiration',
    path: '/api/public/hooks/pass-expiration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBankReconciliationRoute =
  ApiPublicHooksBankReconciliationRouteImport.update({
    id: '/api/public/hooks/bank-reconciliation',
    path: '/api/public/hooks/bank-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/seed-demo': typeof AuthenticatedAdminSeedDemoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/dashboard': typeof AuthenticatedIncidentsDashboardRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/payments/dashboard': typeof AuthenticatedPaymentsDashboardRoute
  '/policies/$policyId': typeof AuthenticatedPoliciesPolicyIdRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/api/public/pdf-smoke': typeof ApiPublicPdfSmokeRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/bank-reconciliation': typeof ApiPublicHooksBankReconciliationRoute
  '/api/public/hooks/pass-expiration': typeof ApiPublicHooksPassExpirationRoute
  '/api/public/hooks/payment-housekeeping': typeof ApiPublicHooksPaymentHousekeepingRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/seed-demo': typeof AuthenticatedAdminSeedDemoRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/dashboard': typeof AuthenticatedIncidentsDashboardRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/payments/dashboard': typeof AuthenticatedPaymentsDashboardRoute
  '/policies/$policyId': typeof AuthenticatedPoliciesPolicyIdRoute
  '/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/api/public/pdf-smoke': typeof ApiPublicPdfSmokeRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/policies': typeof AuthenticatedPoliciesIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/bank-reconciliation': typeof ApiPublicHooksBankReconciliationRoute
  '/api/public/hooks/pass-expiration': typeof ApiPublicHooksPassExpirationRoute
  '/api/public/hooks/payment-housekeeping': typeof ApiPublicHooksPaymentHousekeepingRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/_authenticated/policies': typeof AuthenticatedPoliciesRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/seed-demo': typeof AuthenticatedAdminSeedDemoRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/_authenticated/incidents/dashboard': typeof AuthenticatedIncidentsDashboardRoute
  '/_authenticated/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/_authenticated/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/_authenticated/payments/dashboard': typeof AuthenticatedPaymentsDashboardRoute
  '/_authenticated/policies/$policyId': typeof AuthenticatedPoliciesPolicyIdRoute
  '/_authenticated/policies/new': typeof AuthenticatedPoliciesNewRoute
  '/api/public/pdf-smoke': typeof ApiPublicPdfSmokeRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/policies/': typeof AuthenticatedPoliciesIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/api/public/hooks/bank-reconciliation': typeof ApiPublicHooksBankReconciliationRoute
  '/api/public/hooks/pass-expiration': typeof ApiPublicHooksPassExpirationRoute
  '/api/public/hooks/payment-housekeeping': typeof ApiPublicHooksPaymentHousekeepingRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/dashboard'
    | '/incidents'
    | '/payments'
    | '/policies'
    | '/reports'
    | '/settings'
    | '/admin/seed-demo'
    | '/admin/users'
    | '/clients/new'
    | '/incidents/$incidentId'
    | '/incidents/dashboard'
    | '/incidents/new'
    | '/payments/$paymentId'
    | '/payments/dashboard'
    | '/policies/$policyId'
    | '/policies/new'
    | '/api/public/pdf-smoke'
    | '/clients/'
    | '/incidents/'
    | '/payments/'
    | '/policies/'
    | '/admin/users/$userId'
    | '/api/public/hooks/bank-reconciliation'
    | '/api/public/hooks/pass-expiration'
    | '/api/public/hooks/payment-housekeeping'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/admin/seed-demo'
    | '/clients/new'
    | '/incidents/$incidentId'
    | '/incidents/dashboard'
    | '/incidents/new'
    | '/payments/$paymentId'
    | '/payments/dashboard'
    | '/policies/$policyId'
    | '/policies/new'
    | '/api/public/pdf-smoke'
    | '/clients'
    | '/incidents'
    | '/payments'
    | '/policies'
    | '/admin/users/$userId'
    | '/api/public/hooks/bank-reconciliation'
    | '/api/public/hooks/pass-expiration'
    | '/api/public/hooks/payment-housekeeping'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/incidents'
    | '/_authenticated/payments'
    | '/_authenticated/policies'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/admin/seed-demo'
    | '/_authenticated/admin/users'
    | '/_authenticated/clients/new'
    | '/_authenticated/incidents/$incidentId'
    | '/_authenticated/incidents/dashboard'
    | '/_authenticated/incidents/new'
    | '/_authenticated/payments/$paymentId'
    | '/_authenticated/payments/dashboard'
    | '/_authenticated/policies/$policyId'
    | '/_authenticated/policies/new'
    | '/api/public/pdf-smoke'
    | '/_authenticated/clients/'
    | '/_authenticated/incidents/'
    | '/_authenticated/payments/'
    | '/_authenticated/policies/'
    | '/_authenticated/admin/users/$userId'
    | '/api/public/hooks/bank-reconciliation'
    | '/api/public/hooks/pass-expiration'
    | '/api/public/hooks/payment-housekeeping'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPdfSmokeRoute: typeof ApiPublicPdfSmokeRoute
  ApiPublicHooksBankReconciliationRoute: typeof ApiPublicHooksBankReconciliationRoute
  ApiPublicHooksPassExpirationRoute: typeof ApiPublicHooksPassExpirationRoute
  ApiPublicHooksPaymentHousekeepingRoute: typeof ApiPublicHooksPaymentHousekeepingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies': {
      id: '/_authenticated/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AuthenticatedPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policies/': {
      id: '/_authenticated/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof AuthenticatedPoliciesIndexRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/pdf-smoke': {
      id: '/api/public/pdf-smoke'
      path: '/api/public/pdf-smoke'
      fullPath: '/api/public/pdf-smoke'
      preLoaderRoute: typeof ApiPublicPdfSmokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/policies/new': {
      id: '/_authenticated/policies/new'
      path: '/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof AuthenticatedPoliciesNewRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/policies/$policyId': {
      id: '/_authenticated/policies/$policyId'
      path: '/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof AuthenticatedPoliciesPolicyIdRouteImport
      parentRoute: typeof AuthenticatedPoliciesRoute
    }
    '/_authenticated/payments/dashboard': {
      id: '/_authenticated/payments/dashboard'
      path: '/dashboard'
      fullPath: '/payments/dashboard'
      preLoaderRoute: typeof AuthenticatedPaymentsDashboardRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/payments/$paymentId': {
      id: '/_authenticated/payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/incidents/new': {
      id: '/_authenticated/incidents/new'
      path: '/new'
      fullPath: '/incidents/new'
      preLoaderRoute: typeof AuthenticatedIncidentsNewRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/incidents/dashboard': {
      id: '/_authenticated/incidents/dashboard'
      path: '/dashboard'
      fullPath: '/incidents/dashboard'
      preLoaderRoute: typeof AuthenticatedIncidentsDashboardRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/incidents/$incidentId': {
      id: '/_authenticated/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/seed-demo': {
      id: '/_authenticated/admin/seed-demo'
      path: '/admin/seed-demo'
      fullPath: '/admin/seed-demo'
      preLoaderRoute: typeof AuthenticatedAdminSeedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/api/public/hooks/payment-housekeeping': {
      id: '/api/public/hooks/payment-housekeeping'
      path: '/api/public/hooks/payment-housekeeping'
      fullPath: '/api/public/hooks/payment-housekeeping'
      preLoaderRoute: typeof ApiPublicHooksPaymentHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pass-expiration': {
      id: '/api/public/hooks/pass-expiration'
      path: '/api/public/hooks/pass-expiration'
      fullPath: '/api/public/hooks/pass-expiration'
      preLoaderRoute: typeof ApiPublicHooksPassExpirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bank-reconciliation': {
      id: '/api/public/hooks/bank-reconciliation'
      path: '/api/public/hooks/bank-reconciliation'
      fullPath: '/api/public/hooks/bank-reconciliation'
      preLoaderRoute: typeof ApiPublicHooksBankReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedIncidentsRouteChildren {
  AuthenticatedIncidentsIncidentIdRoute: typeof AuthenticatedIncidentsIncidentIdRoute
  AuthenticatedIncidentsDashboardRoute: typeof AuthenticatedIncidentsDashboardRoute
  AuthenticatedIncidentsNewRoute: typeof AuthenticatedIncidentsNewRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
}

const AuthenticatedIncidentsRouteChildren: AuthenticatedIncidentsRouteChildren =
  {
    AuthenticatedIncidentsIncidentIdRoute:
      AuthenticatedIncidentsIncidentIdRoute,
    AuthenticatedIncidentsDashboardRoute: AuthenticatedIncidentsDashboardRoute,
    AuthenticatedIncidentsNewRoute: AuthenticatedIncidentsNewRoute,
    AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  }

const AuthenticatedIncidentsRouteWithChildren =
  AuthenticatedIncidentsRoute._addFileChildren(
    AuthenticatedIncidentsRouteChildren,
  )

interface AuthenticatedPaymentsRouteChildren {
  AuthenticatedPaymentsPaymentIdRoute: typeof AuthenticatedPaymentsPaymentIdRoute
  AuthenticatedPaymentsDashboardRoute: typeof AuthenticatedPaymentsDashboardRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
}

const AuthenticatedPaymentsRouteChildren: AuthenticatedPaymentsRouteChildren = {
  AuthenticatedPaymentsPaymentIdRoute: AuthenticatedPaymentsPaymentIdRoute,
  AuthenticatedPaymentsDashboardRoute: AuthenticatedPaymentsDashboardRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
}

const AuthenticatedPaymentsRouteWithChildren =
  AuthenticatedPaymentsRoute._addFileChildren(
    AuthenticatedPaymentsRouteChildren,
  )

interface AuthenticatedPoliciesRouteChildren {
  AuthenticatedPoliciesPolicyIdRoute: typeof AuthenticatedPoliciesPolicyIdRoute
  AuthenticatedPoliciesNewRoute: typeof AuthenticatedPoliciesNewRoute
  AuthenticatedPoliciesIndexRoute: typeof AuthenticatedPoliciesIndexRoute
}

const AuthenticatedPoliciesRouteChildren: AuthenticatedPoliciesRouteChildren = {
  AuthenticatedPoliciesPolicyIdRoute: AuthenticatedPoliciesPolicyIdRoute,
  AuthenticatedPoliciesNewRoute: AuthenticatedPoliciesNewRoute,
  AuthenticatedPoliciesIndexRoute: AuthenticatedPoliciesIndexRoute,
}

const AuthenticatedPoliciesRouteWithChildren =
  AuthenticatedPoliciesRoute._addFileChildren(
    AuthenticatedPoliciesRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRouteWithChildren
  AuthenticatedPoliciesRoute: typeof AuthenticatedPoliciesRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminSeedDemoRoute: typeof AuthenticatedAdminSeedDemoRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRouteWithChildren,
  AuthenticatedPoliciesRoute: AuthenticatedPoliciesRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminSeedDemoRoute: AuthenticatedAdminSeedDemoRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPdfSmokeRoute: ApiPublicPdfSmokeRoute,
  ApiPublicHooksBankReconciliationRoute: ApiPublicHooksBankReconciliationRoute,
  ApiPublicHooksPassExpirationRoute: ApiPublicHooksPassExpirationRoute,
  ApiPublicHooksPaymentHousekeepingRoute:
    ApiPublicHooksPaymentHousekeepingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
