CREATE OR REPLACE FUNCTION public.create_payment_schedule_for_policy(_policy_id uuid)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_program_code text;
  v_billing text;
  v_premium numeric(14,2);
  v_default numeric(14,2);
  v_start_date date;
  v_company uuid;
  v_amount numeric(14,2);
  v_is_recurring boolean;
  v_frequency payment_frequency;
  v_schedule_id uuid;
BEGIN
  SELECT pr.code, pr.billing_frequency, p.premium, pr.default_premium, p.start_date, p.company_id
    INTO v_program_code, v_billing, v_premium, v_default, v_start_date, v_company
  FROM public.policies p
  JOIN public.programs pr ON pr.id = p.program_id
  WHERE p.id = _policy_id;

  IF v_program_code IS NULL THEN RAISE EXCEPTION 'policy_not_found'; END IF;
  IF v_company IS NOT NULL THEN RETURN NULL; END IF;
  IF v_start_date IS NULL THEN v_start_date := CURRENT_DATE; END IF;

  v_amount := COALESCE(v_premium, v_default, 0);

  -- Respect the program's configured billing frequency (default yearly).
  IF COALESCE(v_billing, 'yearly') = 'monthly' THEN
    v_is_recurring := true;
    v_frequency := 'monthly';
  ELSE
    v_is_recurring := false;
    v_frequency := 'yearly';
  END IF;

  SELECT id INTO v_schedule_id FROM public.payment_schedules WHERE policy_id = _policy_id LIMIT 1;
  IF v_schedule_id IS NOT NULL THEN
    RETURN v_schedule_id;
  END IF;

  INSERT INTO public.payment_schedules(policy_id, is_recurring, frequency, amount, next_due_date, auto_charge, reminder_days_before)
  VALUES (_policy_id, v_is_recurring, v_frequency, v_amount, v_start_date, false, 10)
  RETURNING id INTO v_schedule_id;

  IF NOT EXISTS (SELECT 1 FROM public.payments WHERE policy_id = _policy_id AND due_date = v_start_date) THEN
    INSERT INTO public.payments(policy_id, amount, due_date, status, payment_schedule_id)
    VALUES (_policy_id, v_amount, v_start_date, 'pending', v_schedule_id);
  END IF;

  RETURN v_schedule_id;
END;
$function$;

-- Fix schedules already created with the wrong monthly frequency on yearly programs.
UPDATE public.payment_schedules ps
SET is_recurring = false, frequency = 'yearly'
FROM public.policies p
JOIN public.programs pr ON pr.id = p.program_id
WHERE ps.policy_id = p.id
  AND ps.frequency = 'monthly'
  AND COALESCE(pr.billing_frequency, 'yearly') <> 'monthly';

-- Remove extra pending monthly payments generated by those wrong schedules
-- (keep the first pending payment per policy; never touch paid/processing rows).
DELETE FROM public.payments pay
USING public.payment_schedules ps, public.policies p, public.programs pr
WHERE pay.payment_schedule_id = ps.id
  AND ps.policy_id = p.id
  AND p.program_id = pr.id
  AND COALESCE(pr.billing_frequency, 'yearly') <> 'monthly'
  AND ps.frequency = 'yearly'
  AND pay.status IN ('pending', 'overdue')
  AND pay.id <> (
    SELECT pay2.id FROM public.payments pay2
    WHERE pay2.policy_id = pay.policy_id
      AND pay2.status IN ('pending', 'overdue')
    ORDER BY pay2.due_date ASC NULLS LAST, pay2.created_at ASC
    LIMIT 1
  );